services:
  db:
    image: postgres:15
    container_name: eopcina-db
    restart: always
    environment:
      - POSTGRES_USER=eopcina_user
      - POSTGRES_PASSWORD=eopcina_password
      - POSTGRES_DB=eopcina_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: ghcr.io/hsadikovic2/eopcina:latest
    container_name: eopcina-app
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=eopcina_db;Username=eopcina_user;Password=eopcina_password

volumes:
  postgres_data: